### ISSUE TITLE
upon installing, running 'make schemas' raises KeyError: 'definitions'

### ISSUE THREAD

**Issue by d3brouille** [GitGuild/sqlalchemy-models#7]
steps to reproduce:
- `git clone https://github.com/GitGuild/sqlalchemy-models.git`
- `cd sqlalchemy-models/`
- `pip install -r requirements.txt`
- `make install`
- `make schemas`

Result:

```
alchemyjsonschema sqlalchemy_login_models.model --out-dir sqlalchemy_login_models/schemas
Traceback (most recent call last):
  File "/home/d3brouille/.local/bin/alchemyjsonschema", line 9, in <module>
    load_entry_point('alchemyjsonschema==0.2.1.1', 'console_scripts', 'alchemyjsonschema')()
  File "/home/d3brouille/.local/lib/python2.7/site-packages/alchemyjsonschema/command.py", line 122, in main
    outdir=args.out_dir, definitions=args.definitions)
  File "/home/d3brouille/.local/lib/python2.7/site-packages/alchemyjsonschema/command.py", line 82, in run
    del definitions[schema['title']]['definitions']
KeyError: 'definitions'
make: *** [schemas] Error 1
```

Is there some undocumented adjustment I need to make?

**Comment by filegeist** [comment]
@isysd After successfully installing Ledger for Python 2.7, I was able to run a few tests.

---

Following @d3brouille 's steps above, `sudo make schemas` still produces the following error:

```
rm -f sqlalchemy_models/*definitions.json
python sqlalchemy_models/util.py sqlalchemy_models/_definitions.json
Traceback (most recent call last):
  File "sqlalchemy_models/util.py", line 79, in <module>
    build_definitions()
  File "sqlalchemy_models/util.py", line 54, in build_definitions
    relation_decision=alchemyjsonschema.RelationDesicion())
  File "/usr/local/lib/python2.7/dist-packages/alchemyjsonschema/command.py", line 82, in run
    del definitions[schema['title']]['definitions']
KeyError: 'definitions'
Makefile:16: recipe for target 'schemas' failed
make: *** [schemas] Error 1

```

---

PR #5 thus does not close this issue, #7 , and issue #8 may still be open, as well, @welshjf .
